import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./views/Navbar";
import Sidebar from "./views/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <body className={`${inter.className} relative mt-24`}>{children}</body>
    </html>
  );
}
